package mock.repository;

import static goorm.deepdive.team1.domain.user.domain.enums.AgeGroups.FIFTIES;
import static goorm.deepdive.team1.domain.user.domain.enums.AgeGroups.FORTIES;
import static goorm.deepdive.team1.domain.user.domain.enums.AgeGroups.SIXTIES_AND_ABOVE;
import static goorm.deepdive.team1.domain.user.domain.enums.AgeGroups.TEENS;
import static goorm.deepdive.team1.domain.user.domain.enums.AgeGroups.THIRTIES;
import static goorm.deepdive.team1.domain.user.domain.enums.AgeGroups.TWENTIES;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;

import goorm.deepdive.team1.domain.user.domain.User;
import goorm.deepdive.team1.domain.user.domain.UserCache;
import goorm.deepdive.team1.domain.user.domain.UserDocument;
import goorm.deepdive.team1.domain.user.domain.enums.AgeGroups;
import goorm.deepdive.team1.domain.user.infrastructure.UserRepository;

public class FakeUserRepository implements UserRepository {
	private final Map<Long, User> users = new ConcurrentHashMap<>();
	private final Map<Long, UserCache> userCaches = new ConcurrentHashMap<>();
	private final Map<String, UserDocument> userDocuments = new ConcurrentHashMap<>();
	private final AtomicLong autoGeneratedId = new AtomicLong(1);

	@Override
	public User save(User user) {
		if (user.getId() == null) {
			User newUser = User.builder()
				.id(autoGeneratedId.getAndIncrement())
				.name(user.getName())
				.email(user.getEmail())
				.phoneNumber(user.getPhoneNumber())
				.address(user.getAddress())
				.gender(user.getGender())
				.age(user.getAge())
				.build();

			if (user.isDeleted()) {
				newUser.markAsDeleted();
			}

			users.put(newUser.getId(), newUser);
			return newUser;
		}

		users.put(user.getId(), user);
		return user;
	}


	@Override
	public Optional<User> findByIdAndDeletedAtIsNull(Long id) {
		return Optional.ofNullable(users.get(id));
	}

	@Override
	public UserCache getUserCache(Long id) {
		return userCaches.get(id);
	}

	@Override
	public void deleteById(Long id) {
		users.remove(id);
		userCaches.remove(id);
		userDocuments.remove(id.toString());
	}

	@Override
	public void saveCache(UserCache userCache) {
		userCaches.put(userCache.getId(), userCache);
	}

	@Override
	public void saveAllCache(List<UserCache> userCaches) {
		userCaches.forEach(this::saveCache);
	}

	@Override
	public void saveDocument(UserDocument userDocument) {
		userDocuments.put(userDocument.getUserId(), userDocument);
	}

	@Override
	public Map<String, Object> searchUserStatistics(List<String> genders, List<String> regions, List<AgeGroups> ageGroups) {
		List<UserDocument> filteredUsers = userDocuments.values().stream()
			.filter(user -> (genders.isEmpty() || genders.contains(user.getGender())))
			.filter(user -> (regions.isEmpty() || regions.contains(user.getRegion())))
			.filter(user -> (ageGroups.isEmpty() || ageGroups.contains(returnGroup(user.getAge()))))
			.toList();

		long totalUsers = filteredUsers.size();

		Map<String, Long> genderStats = genders.stream()
			.collect(Collectors.toMap(
				g -> g,
				g -> filteredUsers.stream().filter(user -> user.getGender().equalsIgnoreCase(g)).count(),
				(a, b) -> b, LinkedHashMap::new));

		Map<String, Long> regionStats = regions.stream()
			.collect(Collectors.toMap(
				r -> r,
				r -> filteredUsers.stream().filter(user -> user.getRegionAddress().equalsIgnoreCase(r)).count(),
				(a, b) -> b, LinkedHashMap::new));

		Map<String, Long> ageStats = ageGroups.stream()
			.collect(Collectors.toMap(
				AgeGroups::getDescription,
				ageGroup -> filteredUsers.stream().filter(user -> returnGroup(user.getAge()) == ageGroup).count(),
				(a, b) -> b, LinkedHashMap::new));

		return Map.of(
			"total", totalUsers,
			"genderStats", genderStats,
			"regionStats", regionStats,
			"ageStats", ageStats
		);
	}


	@Override
	public List<UserDocument> searchHeatMap(List<String> regions, List<AgeGroups> ageGroups) {
		return userDocuments.values().stream()
			.filter(user -> (regions == null || regions.contains(user.getRegion())) &&
				(ageGroups == null || ageGroups.contains(returnGroup(user.getAge()))))
			.collect(Collectors.toList());
	}

	@Override
	public List<Long> findIdsByDeletedAtIsNotNull() {
		return users.values().stream()
			.filter(user -> user.getDeletedAt() == null)
			.map(User::getId)
			.toList();
	}

	@Override
	public void deleteScheduling(List<Long> ids) {
		ids.forEach(this::deleteById);
	}

	@Override
	public Page<UserDocument> searchByName(String name, Pageable pageable) {
		List<UserDocument> result = userDocuments.values().stream()
			.filter(doc -> doc.getName().contains(name))
			.collect(Collectors.toList());
		return new PageImpl<>(result, pageable, result.size());
	}

	@Override
	public Page<UserDocument> searchByRegionAddress(String keyword, Pageable pageable) {
		List<UserDocument> result = userDocuments.values().stream()
			.filter(doc -> doc.getRegionAddress().contains(keyword))
			.collect(Collectors.toList());
		return new PageImpl<>(result, pageable, result.size());
	}

	@Override
	public Page<UserDocument> searchByRoadAddress(String keyword, Pageable pageable) {
		List<UserDocument> result = userDocuments.values().stream()
			.filter(doc -> doc.getRoadAddress().contains(keyword))
			.collect(Collectors.toList());
		return new PageImpl<>(result, pageable, result.size());
	}

	@Override
	public Page<User> findAll(Pageable pageable) {
		List<User> userList = new ArrayList<>(users.values().stream()
			.filter(u -> u.getDeletedAt() == null)
			.toList());
		int start = (int) pageable.getOffset();
		int end = Math.min(start + pageable.getPageSize(), userList.size());
		return new PageImpl<>(userList.subList(start, end), pageable, userList.size());
	}

	@Override
	public Page<UserCache> findAllCache(Pageable pageable) {
		List<UserCache> userList = new ArrayList<>(userCaches.values());
		int start = (int) pageable.getOffset();
		int end = Math.min(start + pageable.getPageSize(), userList.size());
		return new PageImpl<>(userList.subList(start, end), pageable, userList.size());
	}

	private AgeGroups returnGroup(int age) {
		if (age < 10) {
			throw new IllegalArgumentException("10 이상이여야 합니다.");
		} else if (age < 20) {
			return TEENS;
		} else if (age < 30) {
			return TWENTIES;
		} else if (age < 40) {
			return THIRTIES;
		} else if (age < 50) {
			return FORTIES;
		} else if (age < 60) {
			return FIFTIES;
		} else {
			return SIXTIES_AND_ABOVE;
		}
	}
}
