package mock.repository;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

import goorm.deepdive.team1.domain.addresshistory.domain.AddressHistory;
import goorm.deepdive.team1.domain.addresshistory.domain.AddressHistoryCache;
import goorm.deepdive.team1.domain.addresshistory.infrastructure.AddressHistoryRepository;

public class FakeAddressHistoryRepository implements AddressHistoryRepository {
	private final Map<Long, AddressHistory> addressHistories = new ConcurrentHashMap<>();
	private final Map<Long, List<AddressHistoryCache>> addressHistoryCaches = new ConcurrentHashMap<>();
	private final AtomicLong autoGeneratedId = new AtomicLong(1);

	@Override
	public AddressHistory save(AddressHistory addressHistory) {
		if (addressHistory.getId() == null) {
			AddressHistory newAddressHistory = AddressHistory.create(
				addressHistory.getUser(),
				addressHistory.getAddress()
			);
			addressHistories.put(autoGeneratedId.getAndIncrement(), newAddressHistory);
			return newAddressHistory;
		}
		addressHistories.put(addressHistory.getId(), addressHistory);
		return addressHistory;
	}

	@Override
	public List<AddressHistory> findByUserIdAndDeletedAtIsNull(Long userId) {
		return addressHistories.values().stream()
			.filter(addressHistory -> addressHistory.getUser().getId().equals(userId) &&
				!addressHistory.isDeleted())
			.collect(Collectors.toList());
	}

	@Override
	public List<AddressHistoryCache> findCacheByUserIdAndDeletedAtIsNull(Long userId) {
		return addressHistoryCaches.getOrDefault(userId, new ArrayList<>());
	}

	@Override
	public void saveAllCaches(List<AddressHistory> addressHistories) {
		List<AddressHistoryCache> addressHistoryCacheList = addressHistories.stream()
			.map(AddressHistoryCache::from)
			.toList();

		addressHistoryCaches.put(addressHistories.getFirst().getUser().getId(), addressHistoryCacheList);
	}

	@Override
	public void deleteScheduling(List<Long> userIds) {
		userIds.forEach(userId -> {
			addressHistories.values().removeIf(addressHistory -> addressHistory.getUser().getId().equals(userId));
			addressHistoryCaches.remove(userId);
		});
	}
}
