package mock.repository;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

import goorm.deepdive.team1.domain.address.domain.Address;
import goorm.deepdive.team1.domain.address.infrastructure.AddressRepository;
import mock.r.TestEntityUtils;

public class FakeAddressRepository implements AddressRepository {
	private final Map<Long, Address> addresses = new ConcurrentHashMap<>();
	private final AtomicLong autoGeneratedId = new AtomicLong(1);

	@Override
	public Address save(Address address) {
		if (address.getId() == null) {
			Address newAddress = Address.builder()
				.id(autoGeneratedId.getAndIncrement())
				.x(address.getX())
				.y(address.getY())
				.roadAddress(address.getRoadAddress())
				.regionAddress(address.getRegionAddress())
				.region(address.getRegion())
				.build();

			TestEntityUtils.setCreatedAt(newAddress, LocalDateTime.now());
			addresses.put(newAddress.getId(), newAddress);
			return newAddress;
		}

		TestEntityUtils.setCreatedAt(address, LocalDateTime.now());
		addresses.put(address.getId(), address);
		return address;
	}

	@Override
	public Optional<Address> findByRoadAddressContainingAndDeletedAtIsNull(String roadAddress) {
		return addresses.values().stream()
			.filter(address -> address.getDeletedAt() == null)
			.filter(address -> address.getRoadAddress().contains(roadAddress))
			.findFirst();
	}
}
