package mock.repository;

import goorm.deepdive.team1.domain.admin.domain.Admin;
import goorm.deepdive.team1.domain.admin.infrastructure.AdminRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

public class FakeAdminRepository implements AdminRepository {
    private final Map<Long, Admin> admins = new ConcurrentHashMap<>();
    private final AtomicLong autoGeneratedId = new AtomicLong(1);

    @Override
    public Admin save(Admin admin) {
        if (admin.getId() == null) {
            admin = Admin.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .email(admin.getEmail())
                    .password(admin.getPassword())
                    .role(admin.getRole())
                    .build();
        }

        admins.put(admin.getId(), admin);
        return admin;
    }

    @Override
    public Optional<Admin> findByEmail(String email) {
        return admins.values().stream()
                .filter(admin -> admin.getEmail().equals(email))
                .findFirst();
    }

    @Override
    public boolean existsByEmail(String email) {
        return admins.values().stream().anyMatch(admin -> admin.getEmail().equals(email));
    }

    @Override
    public Optional<Admin> findById(Long id) {
        return Optional.ofNullable(admins.get(id));
    }

    @Override
    public void delete(Admin admin) {
        if (admin == null || admin.getId() == null) {
            throw new IllegalArgumentException("권한이 있는 관리자만 삭제할 수 있습니다.");
        }
        admins.remove(admin.getId());
    }

    @Override
    public Page<Admin> findAll(Pageable pageable) {
        List<Admin> adminList = new ArrayList<>(admins.values());
        int start = (int) pageable.getOffset();
        int end = Math.min(start + pageable.getPageSize(), adminList.size());
        return new PageImpl<>(adminList.subList(start, end), pageable, adminList.size());
    }
}
